# Generated by Django 5.0.6 on 2026-07-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_intensity_percent', models.FloatField(default=65.0)),
                ('mode', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('active_policy', models.CharField(blank=True, choices=[('reassure', 'Reassure'), ('awareness', 'Awareness'), ('breath', 'Breath'), ('calm_down', 'Calm Down')], max_length=20, null=True)),
                ('last_bpm', models.IntegerField(blank=True, null=True)),
                ('last_smooth_bpm', models.IntegerField(blank=True, null=True)),
                ('last_baseline_bpm', models.IntegerField(blank=True, null=True)),
                ('last_signal_ok', models.BooleanField(default=False)),
                ('last_phase', models.CharField(default='disconnected', max_length=20)),
                ('arduino_connected', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
        migrations.CreateModel(
            name='MotorCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(choices=[('reassure', 'Reassure'), ('awareness', 'Awareness'), ('breath', 'Breath'), ('calm_down', 'Calm Down')], max_length=20)),
                ('motor_index', models.PositiveSmallIntegerField()),
                ('intensity_percent', models.FloatField(default=70.0)),
            ],
            options={
                'ordering': ['policy', 'motor_index'],
                'unique_together': {('policy', 'motor_index')},
            },
        ),
    ]
